### ISSUE TITLE
[리액트 숙련주차] 개인과제 코드리뷰 - 최원장 튜터

### ISSUE THREAD

**Issue by wonee09** [MyNameSieun/For-You#1]
# 아래 코드리뷰는 props-drilling 브랜치를 기준으로 작성되었습니다.

## 전역 스타일링
![image](https://github.com/MyNameSieun/For-You/assets/62840864/38763400-b287-42b7-b928-c97acfdceeeb)
효율화를 추구할 때, 반복적인 코드를 없애기 위해서 작성한 전역 스타일링 방법 매우 좋습니다!

## state의 적절한 위치
![image](https://github.com/MyNameSieun/For-You/assets/62840864/41d4892c-466e-46d5-9e97-2f60d3cb7392)
writing, detail 페이지 모두 해당 state와 setState 로직을 사용해야 하기 때문에 Router에서 핸들링하는게 적합하다고 볼 수 있겠네요.

## children이 없을 떄는 닫는태그 필요 x
![image](https://github.com/MyNameSieun/For-You/assets/62840864/ad6f9dd4-023f-46b0-a429-f39a9617bce5)
Sidebar는 <Sidebar /> 로 표기할 수 있겠습니다.

## 반복되는 로직에 대한 처리
![image](https://github.com/MyNameSieun/For-You/assets/62840864/e35a1464-f9b4-4b9c-96f8-b474ef90ada8)
<Container> 부분은 모든 컴포넌트를 감싸는 메인 컨테이너이기 때문에 페이지가 생성될 때마다 수기로 넣어주어야 하는 번거로움이 있습니다. Router 단에서 제공할 수도 있을 것 같아요. Outlet 키워드로 검색해보세요 :)

## Home과 Writing이 둘 다 사용하는 Sidebar에 대한 고민
![image](https://github.com/MyNameSieun/For-You/assets/62840864/7751fbca-a327-42d7-8741-48e499c73794)
![image](https://github.com/MyNameSieun/For-You/assets/62840864/b2fb09bd-57e4-4176-8b0b-b741f92bfa2b)
늘 고민해야 하는 것은, 2개 이상 관리될 때 유지보수의 어려움은 없을까? 하는 부분이에요. 시은님이 쓰신 코드도 괜찮아요! 만일, 두 개가 아니라 5개 이상의 많은 컴포넌트가 Sidebar를 사용한다고 하면 어떻게 하면 좋을까요? 모두 갖다 붙이기 보다는 별도 방법을 생각해보는게 좋겠죠?

## 반복 컴포넌트
![image](https://github.com/MyNameSieun/For-You/assets/62840864/f18de2ee-7745-4c70-ac78-132db63be89b)
튜터님 이름에 대한 리스트가 존재한다면, map으로 확장성있게 구현할 수 있는 부분이에요 :)

## ux
![image](https://github.com/MyNameSieun/For-You/assets/62840864/cd029994-5bf9-4a12-b99d-7728c6c6b432)
원치 않는 현상 발생 시, frontend에서 미리 막아주는 습관은 매우 좋죠!! 이런 validation checking, 칭찬합니다 :)

## 3항연산자
![image](https://github.com/MyNameSieun/For-You/assets/62840864/9bbba72f-a8ee-4b15-9226-123f727e4997)
자바스크립트 문법을 react에 잘 녹이기 시작하셨네요 :) 좋습니다.

시은님, redux 까지 꼭꼭 시간내서 작성해보시길 바래요! 질문 있으시면 언제든 오시구요. 고생 많으셨습니다

**Comment by MyNameSieun** [comment]
감사합니다!
